name: train-my-model
on: [push]
jobs:
  train-model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v4       
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          b="${{ secrets.GITHUB_TOKEN }}"
          echo "echo"
          echo "$b"
          echo "echo"
          python train.py

          # Create CML report
          # cml comment create --pr --publish metrics.txt
          cml comment create metrics.txt
